[package]
name = "nmf_pyr"
version = "0.1.0"
edition = "2021"
authors = ["Deron Smith <smith.deron@epa.gov>"]
description = "EPA Environmental Source Apportionment Toolkit (ESAT) Rust Algorithms"
readme = "README.md"
license = "Apache-2.0"
license-file = "LICENSE.txt"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "nmf_pyr"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.18.1"
numpy = "0.18.0"
nalgebra = {version="0.32.2", features = ["rayon"]}
ndarray = "0.15.6"
rayon = "1.7"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 2