[package]
name = "nmf_pyr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "nmf_pyr"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.18.1"
numpy = "0.18.0"
nalgebra = "0.32.2"
ndarray = "0.15.6"
