name: nmf_py
channels:
  - conda-forge
  - defaults
dependencies:
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.5.7
  - certifi=2023.5.7
  - charset-normalizer=3.1.0
  - colorama=0.4.6
  - idna=3.4
  - intel-openmp=2023.1.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libexpat=2.5.0
  - libffi=3.4.2
  - libhwloc=2.9.1
  - libiconv=1.17
  - liblapack=3.9.0
  - libsqlite=3.42.0
  - libxml2=2.11.4
  - libzlib=1.2.13
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - mkl=2022.1.0
  - msys2-conda-epoch=20160418
  - numpy=1.24.3
  - openssl=3.1.1
  - packaging=23.1
  - pandas=2.0.2
  - pip=23.1.2
  - platformdirs=3.5.1
  - pooch=1.7.0
  - pthreads-win32=2.9.1
  - pysocks=1.7.1
  - python=3.11.3
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.11
  - pytz=2023.3
  - requests=2.31.0
  - scipy=1.10.1
  - setuptools=67.7.2
  - six=1.16.0
  - tbb=2021.9.0
  - tk=8.6.12
  - tqdm=4.65.0
  - typing-extensions=4.6.3
  - typing_extensions=4.6.3
  - tzdata=2023c
  - ucrt=10.0.22621.0
  - urllib3=2.0.2
  - vc=14.3
  - vc14_runtime=14.34.31931
  - vs2015_runtime=14.34.31931
  - wheel=0.40.0
  - win_inet_pton=1.1.0
  - xz=5.2.6
  - pip:
    - click==8.1.3
    - fuzzy-c-means==1.7.0
    - joblib==1.2.0
    - maturin==1.0.1
    - pydantic==1.10.8
    - tabulate==0.8.10
    - typer==0.4.2