# esat pyproject.toml for setuptools and setuptools-rust
[build-system]
requires = ["setuptools", "setuptools-rust"]
#requires = ["maturin>=1.0,<2.0"]
#build-backend = "maturin"
build-backend = "setuptools.build_meta"

[project]
name = "esat"
version = "2024.0.1"
requires-python = ">=3.11"
description = "EPA's Environmental Source Apportionment Toolkit python package."
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
    "click>=8.1",
    "fastcluster>=1.2",
    "fuzzy-c-means>=1.7",
    "numpy>=1.26",
    "pandas>=2.2",
    "plotly>=5.19",
    "scipy>=1.12",
    "tqdm>=4.66"
]

[tool.setuptools]
include-package-data = true

[project.scripts]
esat = "cli.esat_cli:esat_cli"

#[tool.maturin]
#features = ["pyo3/extension-module"]
#find = { where = ["python"]}

[tool.setuptools.packages]
find = { where = ["python"]}

[[tool.setuptools-rust.ext-modules]]
target = "esat.esat_rust"
path = "Cargo.toml"
binding = "PyO3"

#[[tool.setup-rust.ext-modules]]
#target = "esat.esat_rust"
#path = "Cargo.toml"
#binding = "PyO3"