# esat pyproject.toml for setuptools and setuptools-rust
[build-system]
requires = ["setuptools", "maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "esat"
version = "2024.0.1"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
    "click>=8.1",
    "fastcluster>=1.2",
    "fuzzy-c-means>=1.7",
    "numpy>=1.26",
    "pandas>=2.2",
    "plotly>=5.19",
    "scipy>=1.12",
    "tqdm>=4.66"
]

[project.scripts]
esat = "cli:main"

[tool.maturin]
features = ["pyo3/extension-module"]

[tool.setuptools.packages]
find = { where = ["python"]}

[[tool.setup-rust.ext-modules]]
target = "esat.esat_rust"
path = "Cargo.toml"
binding = "PyO3"