name: ESAT Code Tests

on:
  push:
    branches:
      - main

jobs:
  build_wheels:
    name: Running coverage pytests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install pytest pytest-cov
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run tests
        run:
            coverage run -m pytest tests