name: Build and Publish Wheel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-13 is an intel runner, macos-14 is apple silicon
        os: [ubuntu-latest, macos-13, macos-14]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install cibuildwheel
        run: |
            python -m pip install --upgrade pip
            curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain=stable
            python -m pip install cibuildwheel==2.17.0 setuptools setuptools-rust
      - name: Build wheels
        run: |
          . "$HOME/.cargo/env"
          echo "${HOME}/.cargo/env" >> $GITHUB_PATH
          python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v4
        with:
          name: esat-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

  build_windows_wheel:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v4

      # Used to host cibuildwheel
      - uses: actions/setup-python@v5
      - name: Install cibuildwheel
        run: |
          python -m pip install --upgrade pip
          curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain=stable
          echo "${HOME}/.cargo/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          python -m pip install cibuildwheel==2.17.0 setuptools setuptools-rust
      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v4
        with:
          name: esat-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl