name: Build and Publish Artifacts

on:
  push:
    branches:
      - dev

env:
  MACOSX_DEPLOYMENT_TARGET: "10.12"
  CIBW_BUILD: "cp310-* cp311-* cp312-*"

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13, macos-14]
        python_version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install setuptools
        run: |
          python -m pip install --upgrade pip
          curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain=stable
          echo "PATH=${PATH}:${HOME}/.cargo/bin" >> "$GITHUB_ENV"
          rustc --version
          python -m pip install build setuptools setuptools-rust
      - name: Build CPU wheels with cibuildwheel
        run: |
          python -m pip install cibuildwheel==2.22.0
          python -m cibuildwheel --output-dir wheelhouse
      - uses: actions/upload-artifact@v4
        with:
          name: esat-wheels-cpu-${{ matrix.os }}-py${{ matrix.python_version }}
          path: ./wheelhouse/*.whl
      - name: Build GPU wheels with cibuildwheel
        run: |
          rm -rf wheelhouse
          python -m pip install cibuildwheel==2.22.0
          python -m cibuildwheel --output-dir wheelhouse
      - uses: actions/upload-artifact@v4
        with:
          name: esat-wheels-gpu-${{ matrix.os }}-py${{ matrix.python_version }}
          path: ./wheelhouse/*.whl

  build_windows_wheel:
    name: Build wheels on windows-latest
    runs-on: windows-latest
    strategy:
      matrix:
        python_version: [ "3.10", "3.11", "3.12" ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install setuptools
        run: |
          python -m pip install --upgrade pip
          curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain=stable
          rustup target add aarch64-pc-windows-msvc i686-pc-windows-msvc x86_64-pc-windows-msvc
          echo "${HOME}/.cargo/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          python -m pip install build setuptools setuptools-rust
      - name: Build CPU wheels with cibuildwheel
        run: |
          python -m pip install cibuildwheel==2.22.0
          python -m cibuildwheel --output-dir wheelhouse
      - uses: actions/upload-artifact@v4
        with:
          name: esat-wheels-cpu-windows-py${{ matrix.python_version }}
          path: ./wheelhouse/*.whl
      - name: Build GPU wheels with cibuildwheel
        run: |
          Remove-Item -Recurse -Force wheelhouse
          python -m pip install cibuildwheel==2.22.0
          python -m cibuildwheel --output-dir wheelhouse
      - uses: actions/upload-artifact@v4
        with:
          name: esat-wheels-gpu-windows-py${{ matrix.python_version }}
          path: ./wheelhouse/*.whl